services:
  - type: web
    name: flask-quiz
    runtime: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: quiz-db
          property: 1ce14d265245d44a72ef5f57cec76a5a
    region: oregon